spring:
  application:
    name: cloud-app
  # elasticsearch配置
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.172.96.135:9300
      repositories:
        enabled: true
  # 数据库 配置
  datasource:
    url: jdbc:oracle:thin:@47.103.27.25:1521:xe
    username: cloud
    password: gaosanshi
    #   driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver

  # JPA 配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
# 端口号
server:
  port: 9999
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost

# ===== 自定义swagger配置 ===== #
#swagger:
#  enable: true
#  application-name: ${spring.application.name}
#  application-version: 1.0
#  application-description: Cloud-App Study Record
#  try-host: http://localhost:${server.port}

