spring:
  application:
    name: feign-service
# 端口号
server:
  port: 8765
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
# hystrix (Feign是自带断路器的，在低版本的Spring Cloud中，它没有默认打开）
feign:
  hystrix:
    enabled: true
