spring:
  application:
    name: zuul-service
# 端口号
server:
  port: 8769
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-service
    api-b:
      path: /api-b/**
      serviceId: feign-service
