spring:
  application:
    name: eureka-server
# 端口号
server:
  port: 8000
# eureka配置
eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka Server，默认为true。
    fetch-registry: false #是否从Eureka Server获取注册信息，默认为true
    serviceUrl:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
      #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost