spring:
  application:
    name: eureka-service
# 端口号
server:
  port: 8001
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/
  instance:
    hostname: localhost