spring:
  application:
    name: eureka-service
# 端口号
server:
  port: 8762
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost