spring:
  application:
    name: ribbon-service
# 端口号
server:
  port: 8763
# eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream